---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1118216/public_html/
    - /bin/cp -R /semesta/application/controllers $DEPLOYPATH
    - /bin/cp -R /semesta/application/helpers $DEPLOYPATH
    - /bin/cp -R /semesta/application/models $DEPLOYPATH
    - /bin/cp -R /semesta/application/views $DEPLOYPATH
    